import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { emergencyRows, telHref } from '../src/lib/emergency.js';

describe('emergency numbers', () => {
  it('merges identical numbers into one row', () => {
    expect(emergencyRows({ police: '911', fire: '911', ambulance: '911', main: '911', mainNote: null })).toEqual([
      { label: 'Police, fire & ambulance', number: '911', note: null },
    ]);
  });
  it('lists separate services and an extra main number', () => {
    expect(emergencyRows({ police: '113', fire: '115', ambulance: '118', main: '112', mainNote: null })).toEqual([
      { label: 'Emergency', number: '112', note: null },
      { label: 'Police', number: '113', note: null },
      { label: 'Ambulance', number: '118', note: null },
      { label: 'Fire', number: '115', note: null },
    ]);
    expect(emergencyRows({ police: '191', fire: '199', ambulance: '1669', main: '1669', mainNote: null }).map((r) => r.label)).toEqual(['Police', 'Ambulance', 'Fire']);
    expect(emergencyRows({ police: '999', fire: '999', ambulance: '112', main: '999', mainNote: '999 or 112' })[0]).toEqual({ label: 'Police & fire', number: '999', note: '999 or 112' });
  });
  it('handles missing data', () => {
    expect(emergencyRows(null)).toEqual([]);
    expect(emergencyRows({ police: null, fire: null, ambulance: null, main: '000', mainNote: null })).toEqual([{ label: 'Emergency', number: '000', note: null }]);
  });
  it('builds safe tel: links', () => {
    expect(telHref('772-03-73')).toBe('tel:7720373');
    expect(telHref('13 11 14')).toBe('tel:131114');
    expect(telHref('"><script>')).toBe('tel:');
  });
  it('generated dataset keeps leading zeros and covers major countries', () => {
    const file = path.resolve(import.meta.dirname, '../public/geo/emergency-numbers.json');
    if (!fs.existsSync(file)) return; // generated by `npm run prepare:geo`
    const { countries } = JSON.parse(fs.readFileSync(file, 'utf8'));
    expect(countries.AU.main).toBe('000');
    expect(countries.US.main).toBe('911');
    expect(countries.IT).toMatchObject({ main: '112', police: '113' });
    for (const cc of ['GB', 'DE', 'FR', 'JP', 'IN', 'BR', 'TH', 'CN', 'ZA', 'MX']) expect(countries[cc], cc).toBeTruthy();
    for (const e of Object.values(countries)) for (const v of [e.police, e.fire, e.ambulance]) expect(v).not.toBe('0');
  });
});
