#!/usr/bin/env node
// Write dist/sw.js after `vite build`: a service worker that makes the site work
// offline and installable.
//
//  * App shell (HTML, JS, CSS, icons, bundled geography + emergency numbers):
//    precached on install, served cache-first. The cache name includes a hash
//    of the file list, so each deploy replaces the old shell.
//  * Published data (./data/…): network-first. The latest successful response
//    is kept (keyed without the version query) and used when offline, so the
//    page shows the last data this device saw — with its real timestamps.
//  * Basemap tiles/styles/fonts (OpenFreeMap): stale-while-revalidate with a
//    size cap, so areas you have viewed (or saved for offline) still draw.
//  * Search (Nominatim): never cached by the worker.

import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { ROOT } from './lib/config.js';

const dist = path.join(ROOT, 'dist');
const files = [];
async function walk(dir) {
  for (const e of await fs.readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) await walk(p);
    else files.push(path.relative(dist, p).split(path.sep).join('/'));
  }
}
await walk(dist);

// Data is cached at runtime (network-first); maps are cached as they are viewed.
const precache = files.filter((f) => !f.startsWith('data/') && f !== 'sw.js' && !f.endsWith('.map')).sort();
const hash = crypto.createHash('sha256');
for (const f of precache) hash.update(f).update(await fs.readFile(path.join(dist, f)));
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
// Cache lookups use ignoreVary: servers may send "Vary: Origin", and module
// scripts carry an Origin header that precached requests do not.
const VERSION = ${JSON.stringify(version)};
const SHELL = 'gim-shell-' + VERSION;
const DATA = 'gim-data-v1';
const TILES = 'gim-basemap-v1';
const MAX_TILES = 2500;
const PRECACHE = ${JSON.stringify(['./', ...precache.map((f) => `./${f}`)], null, 0)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(SHELL).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('gim-shell-') && k !== SHELL).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

const stripSearch = (url) => { const u = new URL(url); u.search = ''; return u.toString(); };

async function networkFirstData(request) {
  const cache = await caches.open(DATA);
  const key = stripSearch(request.url);
  try {
    const res = await fetch(request);
    if (res.ok) await cache.put(key, res.clone());
    return res;
  } catch (e) {
    const hit = await cache.match(key, { ignoreVary: true });
    if (hit) return hit;
    throw e;
  }
}

async function trimTiles(cache) {
  const keys = await cache.keys();
  for (let i = 0; i < keys.length - MAX_TILES; i++) await cache.delete(keys[i]);
}

async function staleWhileRevalidate(event, request) {
  const cache = await caches.open(TILES);
  const hit = await cache.match(request, { ignoreVary: true });
  const update = fetch(request)
    .then(async (res) => {
      if (res.ok) {
        await cache.put(request, res.clone());
        trimTiles(cache);
      }
      return res;
    })
    .catch(() => hit);
  if (hit) {
    event.waitUntil(update.catch(() => {}));
    return hit;
  }
  return update;
}

async function shell(request) {
  const hit = await caches.match(request, { ignoreSearch: true, ignoreVary: true });
  if (hit) return hit;
  return fetch(request);
}

async function navigation(request) {
  try {
    return await fetch(request);
  } catch {
    const url = new URL(request.url);
    const page = url.pathname.endsWith('.html') ? url.pathname.split('/').pop() : 'index.html';
    const opts = { ignoreSearch: true, ignoreVary: true };
    return (await caches.match('./' + page, opts)) || (await caches.match('./', opts)) || Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin === self.location.origin) {
    if (request.mode === 'navigate') return event.respondWith(navigation(request));
    if (url.pathname.includes('/data/')) return event.respondWith(networkFirstData(request));
    return event.respondWith(shell(request));
  }
  if (url.hostname === 'tiles.openfreemap.org') return event.respondWith(staleWhileRevalidate(event, request));
});
`;
await fs.writeFile(path.join(dist, 'sw.js'), sw);
console.log(`Service worker written (version ${version}, ${precache.length} precached files).`);
